# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cbe16c009b78096cdf1b79572014a66963796db246128fca12176f4ab6d780c3c71bf03450761341e15961a96a403a15db1e0f788be629e578ec82ffce78b1b

test:
  secret_key_base: 7303355196f2f5d0870d39c5ae7e31ace2d7dff3f289fbef9c061fcea916c34e472a9771fed604a61bf4795df0148e24ceb0b7b2707a6a6bcfbef6d04fefb705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
