---

- name: Install Apache2 + mod-shib2
  apt: name={{item}} state=present
  with_items:
    - apache2
    - apache2-dev
    - libcurl4-openssl-dev
    - libapache2-mod-shib2

- name: Remove default Apache2 welcome site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Remove default Apache2 welcome site files
  file: path=/var/www/html state=absent

- name: Enable mod-shib2
  command: a2enmod shib2 creates=/etc/apache2/mods-enabled/shib2.load

- name: Enable mod-ssl
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load

- name: Create self-signed certificate
  command: openssl req -new -nodes -x509 -subj "/C=GB/ST=London/L=London/O=IT/CN={{ site_domain }}" -days 365 -keyout "/etc/ssl/private/{{ site_domain }}.key" -out /etc/ssl/certs/{{ site_domain }}.crt -extensions v3_ca creates=/etc/ssl/certs/{{ site_domain }}.crt
- file: path=/etc/ssl/private/{{ site_domain }}.key owner=root group=ssl-cert

- name: generate SP key
  command: shib-keygen creates=/etc/shibboleth/sp-key.pem

- name: shibboleth2.xml config
  template: src=shibboleth2.xml.j2 dest=/etc/shibboleth/shibboleth2.xml

- name: XML is like violence - if it doesn't work - use more.
  shell: shib-metagen -c /etc/ssl/certs/{{ site_domain }}.crt -h {{ site_domain }} > /etc/shibboleth/{{ site_domain }}-metadata.xml

- service: name=shibd state=restarted
- service: name=apache2 state=restarted