---

- name: Install Apache2 + mod-shib2
  apt: name={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-shib2

- name: Remove default Apache2 welcome site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Remove default Apache2 welcome site files
  file: path=/var/www/html state=absent

- name: Enable mod-shib2
  command: a2enmod shib2 creates=/etc/apache2/mods-enabled/shib2.load

- name: Create "Private Site" configuration
  template: src=private-site.conf.j2 dest=/etc/apache2/sites-available/100-private-site.conf

- name: Enable "Private Site"
  command: a2ensite 100-private-site creates=/etc/apache2/sites-enabled/100-private-site.conf

- name: Private site folder
  file: path={{ item }} state=directory owner={{ site_owner }} group={{ site_group }}
  with_items:
    - '/var/www/{{ site_domain }}'
    - '/var/www/{{ site_domain }}/public_html'
    - '/var/www/{{ site_domain }}/public_html/private'
    - '/var/www/{{ site_domain }}/log'

- name: Create self-signed certificate
  command: openssl req -new -nodes -x509 -subj "/C=GB/ST=London/L=London/O=IT/CN={{ site_domain }}" -days 365 -keyout "/etc/ssl/private/{{ site_domain }}.key" -out /etc/ssl/certs/{{ site_domain }}.crt -extensions v3_ca creates=/etc/ssl/certs/{{ site_domain }}.crt
- file: path=/etc/ssl/private/{{ site_domain }}.key owner=root group=ssl-cert

- name: XML is like violence - if it doesn't work - use more.
  shell: shib-metagen -c /etc/ssl/certs/{{ site_domain }}.crt -h {{ site_domain }} > /etc/shibboleth/{{ site_domain }}-metadata.xml

- service: name=shibd state=restarted
- service: name=apache2 state=restarted