---

- name: Install
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.3
    - postgresql-client

- name: Install pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=0640 backup=yes

# TODO: most likely not required
- name: Enable local access
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
    backup=yes
    regexp='^#?listen_addresses\s*='
    line="listen_addresses = '*'"
    state=present

- name: Restart
  service:
    name: postgresql
    state: restarted
