---

- name: Install PHP5 Apache mod
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php5

- name: Enable mod-php5
  command: a2enmod php5

- service: name=apache2 state=restarted
